package org.example.model;

import jakarta.persistence.*;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

@Entity // Student is an entity class //why is Student an entity class? // Student is an entity class because it is annotated with the @Entity annotation
@Table(name = "students")
// 4. Using Named Query
//@NamedQuery(name="Student.findByAttributeName",
//            query = "SELECT st FROM Student st WHERE st.name = :name" )
public class Student {

    @Id //ID is the primary key for the table students in the database //why is ID the primary key for the table students in the database? // ID is the primary key for the table students in the database because it is annotated with the @Id annotation
    @GeneratedValue(strategy = GenerationType.AUTO) // ID is auto-generated by the database when a new student is added to the table students //why is ID auto-generated by the database when a new student is added to the table students? // ID is auto-generated by the database when a new student is added to the table students because it is annotated with the @GeneratedValue(strategy = GenerationType.AUTO) annotation
    @Column(name = "id", nullable = false) // ID is a column in the table students and cannot be null //why is ID a column in the table students and cannot be null? // ID is a column in the table students and cannot be null because it is annotated with the @Column(name = "id", nullable = false) annotation
    private Long id; // ID is a Long type variable //why is ID a Long type variable? // ID is a Long type variable because it is declared as a Long type variable

    @Column(nullable = false) // name is a column in the table students and cannot be null //why is name a column in the table students and cannot be null? // name is a column in the table students and cannot be null because it is annotated with the @Column(nullable = false) annotation
    private String name; // name is a String type variable //why is name a String type variable? // name is a String type variable because it is declared as a String type variable

    @DateTimeFormat(pattern = "yyyy-MM-dd") // enrollmentDate is a column in the table students //why is enrollmentDate a column in the table students? // enrollmentDate is a column in the table students because it is annotated with the @DateTimeFormat(pattern = "yyyy-MM-dd") annotation
    private Date enrollmentDate; // enrollmentDate is a Date type variable //why is enrollmentDate a Date type variable? // enrollmentDate is a Date type variable because it is declared as a Date type variable


    // courses is a column in the table students //why is courses a column in the table students? // courses is a column in the table students because it is annotated with the @Column annotation

    private String courses;


    // default constructor for the Student class //why is there a default constructor for the Student class? // There is a default constructor for the Student class because it is used to create new instances of the Student class
    public Student() {
    }
 // parameterized constructor with name, enrollmentDate, and courses as parameters
    public Student(String name, Date enrollmentDate, String courses) {
        this.name = name;
        this.enrollmentDate = enrollmentDate;
        this.courses = courses;
    }

    public Long getId() {
        return id;

    }


    // getter and setter methods for the variables in the Student class
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Date getEnrollmentDate() {
        return enrollmentDate;
    }

    public void setEnrollmentDate(Date enrollmentDate) {
        this.enrollmentDate = enrollmentDate;
    }

    public String getCourses() {
        return courses;
    }

    public void setCourses(String courses) {
        this.courses = courses;
    }
}
